# Permalinks
permalink:           pretty

# Setup
title:               Rai Technology
tagline:             Financial technology. Done elegantly.
url:                 https://raitechnology.github.io
paginate:            5
baseurl:             ""
analytics_id:        UA-xxxxx

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Rai
  url:
  email:             support@raitechnology.com

# Gems
gems:
  - jekyll-paginate
  - jekyll-asciidoc
